model:
    arch: hardnet
data:
    dataset: pascal
    train_split: train
    val_split: val
    img_rows: 512
    img_cols: 512
    path: /content/VOCdevkit/VOC2012/
    sbd_path: /content/VOCdevkit/benchmark/benchmark_RELEASE/
training:
    train_iters: 100000
    batch_size: 8
    val_interval: 1000
    n_workers: 4
    print_interval: 10
    augmentations:
        hflip: 0.5
        rscale_crop: [512,512]
    optimizer:
        name: 'sgd'
        lr: 0.01
        weight_decay: 0.0005
        momentum: 0.9
    loss:
        name: 'bootstrapped_cross_entropy'
        min_K: 4096
        loss_th: 0.3
        size_average: True
    lr_schedule:
        name: 'poly_lr'
        max_iter: 100000
    resume: None
    finetune: None
